#- title: Cloud
#  fulltitle: IoT Hub
#  description: IoT Hub Documentation
#  tag: paas
#  icon: /images/thingsboard-c-icon.svg
#  path: /docs/paas/
#  guides: /docs/paas/guides/
#  getStarted: /docs/paas/getting-started-guides/helloworld/
#  docsPrefix: /docs/paas/
- title: IoT Hub
  fulltitle: IoT Hub
  description: IoT Hub Documentation
  tag: pe
  icon: /images/IoT_4_512.png
  path: /docs/pe/
  guides: /docs/pe/guides/
  getStarted: /docs/pe/getting-started-guides/helloworld/
  docsPrefix: /docs/pe/
#- title: Community Edition
#  fulltitle: IoT Hub Community Edition
#  description: IoT Hub Documentation
#  tag: ce
#  icon: /images/thingsboard-cm-icon.svg
#  path: /docs/
#  guides: /docs/guides/
#  getStarted: /docs/getting-started-guides/helloworld/
#  docsPrefix: /docs/
#- title: IoT Gateway
#  fulltitle: IoT Hub IoT Gateway
#  description: IoT Hub Documentation
#  tag: gw
#  icon: /images/gateway-icon.svg
#  path: /docs/iot-gateway/
#  getStarted: /docs/iot-gateway/getting-started/
#- title: License Server
#  fulltitle: IoT Hub License Server
#  description: IoT Hub Documentation
#  tag: license
#  icon: /images/license-icon.svg
#  path: /products/license-server/
#- title: Trendz Analytics
#  fulltitle: Trendz Analytics
#  description: Trendz Documentation
#  tag: trendz
#  icon: /images/trendz-icon.svg
#  path: /docs/trendz/
#  getStarted: /docs/trendz/getting-started/
